# Generated by Django 6.0.1 on 2026-03-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnhanceLearn', '0002_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnhanceLearn.kelas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
