# Generated by Django 6.0.1 on 2026-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnhanceLearn', '0004_hasilkuis'),
    ]

    operations = [
        migrations.CreateModel(
            name='KKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=75)),
            ],
        ),
    ]
