# Generated by Django 6.0.1 on 2026-04-11 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnhanceLearn', '0005_kkm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkm',
            name='nilai',
            field=models.IntegerField(default=70),
        ),
        migrations.CreateModel(
            name='ProgressMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('aktivitas_selesai', models.IntegerField(default=0)),
                ('kuis_selesai', models.IntegerField(default=0)),
                ('terakhir_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
