# Generated by Django 6.0.1 on 2026-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnhanceLearn', '0007_aktivitasselesai'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilkuis',
            name='detail_soal',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
